### ISSUE TITLE
Publish site every 4 hours.

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/philips-software.github.io#1]
Publish site every 4 hours.

```
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */4 * * *'
```
